spring:
  datasource:
    url: jdbc:sqlite:sqlite.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb+srv://min1925k:50c1hxznM47soeCa@cluster0.feqdlxq.mongodb.net/chatHistory?retryWrites=true&w=majority&appName=Cluster0&authSource=admin
